### PR TITLE
Remove lazy_static

### PR DESCRIPTION
**Pull request by csking101**
#42 
Removed `lazy_static` and implemented `OnceLock`

### CODE REVIEW

**Review by gabhijit — CHANGES_REQUESTED** [review]
Looks Good to me! Can you rebase and squash this into a single commit - so that I can merge this directly!

**Comment by csking101** [comment]
I'd rebased already it in the force push, do I need to do it once again to squash into a single commit?

**Comment by gabhijit** [comment]
What I generally do is - if there are more than one commits - Just squash into one logical commit, so that the history looks okay. I can do it for you as well. But if you do it, I will just merge it.

**Comment by csking101** [comment]
I have tried squashing it now, could you please check sir.

**Review by gabhijit — APPROVED** [review]

**Comment by gabhijit** [comment]
@csking101 : I have made minor edits to the git commit message and then merged that. This functionality is now available in the main branch.

Thank you for your contribution.

**Pull request closed without merging**
