### PR TITLE
Fix DNS Packet Dissection and Deserialization

### LINKED ISSUE #25: Error during dissection of DNS packets
During dissection of DNS packets, it appears that the packet is alright and data is also available but we get `TooShort` Error. Below is the dump of the Error and the data 

```bash
Err: TooShort { required: 20, available: 9, data: "07080000038400093a800001518000002904d0000000000000" }, data: "000000010006001a9adead05000008004500008eee3240003611927701010101c0a8010b0035c441007a2f68f60c81a300010000000100010a6964656e7469747964620000010001000006000100014e51004001610c726f6f742d73657276657273036e657400056e73746c640c766572697369676e2d67727303636f6d007896689d000007080000038400093a800001518000002904d0000000000000"
```

### PR DESCRIPTION
**Pull request by aadilshabier**
- Fix fmt() for DNSName
- Fix #25

### CODE REVIEW

**Comment by gabhijit** [comment]
@aadilshabier : There are a couple of tests failing. I have not looked at it. Let me know should I take a look.

**Comment by aadilshabier** [comment]
> @aadilshabier : There are a couple of tests failing. I have not looked at it. Let me know should I take a look.

One of the tests, `packet::tests::parse_failing` packet was actually a valid packet according to Wireshark. So I ignored the test for now. The other test should pass now.

**Review by gabhijit — APPROVED** [review]
Looks Good! I am making a few changes locally in this branch and then will merge this branch! For instance, I changed the `failing` tests to test for `is_ok()` and error out otherwise. All the previously failing tests should pass.

**Comment by gabhijit** [comment]
This is merged into the master now!! Thank you for your contribution.

**Pull request closed without merging**
